direction: right

RilevazioneDatiInTempoReale: "C1: Rilevazione dati in tempo reale" {
  AcquisizioneMovimento: {shape: class}
  AcquisizioneParametriSanitari: {shape: class}
}

RilevazioneDatiInTempoReale.AcquisizioneMovimento -> ActiveStateless
RilevazioneDatiInTempoReale.AcquisizioneParametriSanitari -> ActiveStateful


RilevazioneEGestioneAnomalie: "C2: Rilevazione e gestione anomalie" {
  RilevazioneAnomalie: {shape: class}
  GestioneAnomalie: {shape: class}
}
RilevazioneEGestioneAnomalie.RilevazioneAnomalie -> ActiveStateless
RilevazioneEGestioneAnomalie.GestioneAnomalie -> ActiveStateful


GestioneEControlloPianiTerapeutici: "C3: Gestione e controllo piani terapeutici" {
  GestionePianiTerapeutici: {shape: class}
  ControlloPianiTerapeutici: {shape: class}
}
GestioneEControlloPianiTerapeutici.GestionePianiTerapeutici -> PassiveStateless
GestioneEControlloPianiTerapeutici.ControlloPianiTerapeutici -> ActiveStateless


InterfacciaMedicale: "C4: Interfaccia Medicale" {
  InterfacciaMedicale: {shape: class}
}
InterfacciaMedicale.InterfacciaMedicale -> PassiveStateless
